AWSTemplateFormatVersion: '2010-09-09'
Description: >
  [Creates a RDS instance with password from secret manager. RDS, Subnet group, Security groups, Secret manager with auto rotation of password, VPC endpoint for Secret manager]
  [Documentation: Refer the output section for documentation.]
  [Author: Rajesh Raveendran]
  [Version: 1.0.0]
  [Date: 11-08-2025]

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select the VPC from below list, where the RDS to be deployed.
  VpcCidr:
    Type: String
    Description: Provide the CIDR where from the RDS to be accessed.
    Default: 10.10.0.0/24
  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: "Select a subnet from one AZ"
  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: "Select a subnet from another AZ"
  
Resources:
################## Secret Manager ####################################################
  RdsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: RdsSecret
      Description: "Admin credentials with random password for RDS"
      GenerateSecretString:
        SecretStringTemplate: '{"username":"admin"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\'  # Optional - exclude confusing/special characters
        ExcludePunctuation: true   # Optional - exclude all punctuation
        RequireEachIncludedType: true
      Tags:
        - Key: Name
          Value: RdsSecret

  SecretRotationLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: RdsSecretRotationLambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole 

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Lambda to reach RDS and Secrets Manager
      VpcId: !Ref VpcId
      GroupName: LambdaSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref VpcCidr # Or better: only the VPC endpoint’s private IP range
      Tags:
        - Key: Name
          Value: LambdaSecurityGroup

  SecretsManagerVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.secretsmanager
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      SecurityGroupIds:
        - !Ref LambdaSecurityGroup

  SecretRotationLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: RdsSecretRotation
      Runtime: python3.11
      Role: !GetAtt SecretRotationLambdaRole.Arn
      Handler: lambda_function.lambda_handler
      Timeout: 300
      MemorySize: 128
      VpcConfig:
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
      Code:
        S3Bucket: aws-lanbda-functions-repo1
        S3Key: lambda_function.zip
      # Note: Download the file from below location and upload to a local region bucket in your account and refer those details in above two lines
      # https://aws-lanbda-functions-repo.s3.us-east-1.amazonaws.com/aws-secrets-manager-rotation-lambdas/SecretsManagerRDSMySQLRotationSingleUser/lambda_function.zip
      Environment:
        Variables:
          SECRETS_MANAGER_ENDPOINT: !Sub "https://secretsmanager.${AWS::Region}.amazonaws.com"

  LambdaPermissionForSecretsManager:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SecretRotationLambda
      Action: lambda:InvokeFunction
      Principal: secretsmanager.amazonaws.com

  RdsSecretRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    DependsOn: SecretRotationLambda
    Properties:
      SecretId: !Ref RdsSecret
      RotationLambdaARN: !GetAtt SecretRotationLambda.Arn
      RotationRules:
        AutomaticallyAfterDays: 30   # Rotate every 30 days
################## Secret Manager Ends Here ##########################################
#
#
#
#
################## RDS Instance ######################################################
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to RDS
      GroupName: RdsSecurityGroup
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: !Ref VpcCidr  # Allow access only from this CIDR
      Tags:
        - Key: Name
          Value: RdsSecurityGroup

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds:
        - !Ref PrivateSubnet1    
        - !Ref PrivateSubnet2   
      Tags:
        - Key: Name
          Value: DBSubnetGroup

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: RDS-Instance-mysql
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      Engine: mysql
      MasterUsername: !Sub '{{resolve:secretsmanager:${RdsSecret}::username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${RdsSecret}::password}}'
      PubliclyAccessible: false
      BackupRetentionPeriod: 7
      StorageType: gp3
      MultiAZ: false
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      DeletionProtection: false

  RDSSecretTargetAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref RdsSecret
      TargetId: !Ref DBInstance
      TargetType: AWS::RDS::DBInstance
################## RDS Instance Ends here ############################################

Outputs:
  RDSInstanceEndpoint:
    Description: The endpoint of the RDS instance
    Value: !GetAtt DBInstance.Endpoint.Address

  ArchitectureDiagram:
    Description: "Link to architectural diagram"
    Value: "https://github.com/rajeshraveendra/AWS_Solutions/wiki/RDS-with-Secret-Manager-Autorotation"